const fs = require('fs');

let content = fs.readFileSync('src/data/shafiee-da-al-ayyam/poemData.ts', 'utf8');

const massiveQuatrains = `  quatrains: [
    {
      id: 1,
      lineIndices: [1, 2, 3, 4],
      mlMeaning: "കാലത്തിന്റെ ഗതിവിഗതികളെ അതിന്റെ വഴിക്ക് വിടുക, അല്ലാഹുവിന്റെ വിധിയിൽ പൂർണ്ണ തൃപ്തി കണ്ടെത്തുക. രാത്രികളുടെ ദുരന്തങ്ങളിൽ പതറരുത്, കാരണം ഈ ലോകത്തെ ഒരു ദുരന്തവും ശാശ്വതമല്ല. മനുഷ്യ ജീവിതത്തിൽ എപ്പോഴും മാറ്റങ്ങൾ സംഭവിച്ചുകൊണ്ടിരിക്കും. സന്തോഷവും ദുഃഖവും ഇടകലർന്നതാണ് ഈ ജീവിതം. അതുകൊണ്ട് തന്നെ കാലം വരുത്തുന്ന മാറ്റങ്ങളിൽ അതൃപ്തി കാണിക്കരുത്. എന്ത് സംഭവിച്ചാലും അത് അല്ലാഹുവിന്റെ തീരുമാനമാണെന്ന് വിശ്വസിച്ച് മനസ്സമാധാനം കണ്ടെത്തുക. ജീവിക്കുന്ന ചുറ്റുപാടുകളിൽ വലിയ പ്രതിസന്ധികൾ വരുമ്പോൾ പലരും ഭയന്ന് പിന്മാറാറുണ്ട്. എന്നാൽ ഒരു യഥാർത്ഥ വിശ്വാസി ഒരിക്കലും അങ്ങനെ ചെയ്യാൻ പാടില്ല. ഏത് വലിയ പ്രതിസന്ധിക്കും ഒരു അവസാനമുണ്ട്. രാത്രിയിലെ ഇരുട്ടിന് ശേഷം പകലിന്റെ വെളിച്ചം വരുന്നത് പോലെ കഷ്ടപ്പാടുകൾക്ക് ശേഷം തീർച്ചയായും ആശ്വാസം വരും.",
      enMeaning: "Leave the days to unfold as they will, and find absolute peace in the divine decree. Never panic at the calamities brought by the nights, for no hardship in this transient world is eternal. Human life is a constantly changing tapestry of joy and sorrow. Therefore, do not be dissatisfied with the changes brought by time. Whatever happens, find inner peace by believing that it is the will and decree of Allah. When immense crises arise in one's environment, many shrink back in fear and despair. However, a true believer must never do so. Every great crisis has an end. Just as the light of day follows the darkness of night, relief will undoubtedly follow hardship.",
      arSharah: "يبدأ الإمام الشافعي هذه القصيدة العظيمة بوضع حجر الأساس للراحة النفسية والطمأنينة القلبية، ألا وهو الرضا بقضاء الله وقدره. في قوله 'دع الأيام تفعل ما تشاء'، دعوة صريحة لترك التدبير المطلق لله سبحانه وتعالى، وعدم معاندة حركة الزمن وتغيراته. فالأيام تتقلب بين يسر وعسر، وصحة ومرض، وغنى وفقر. الإنسان الحكيم هو الذي يتكيف مع هذه التقلبات بروح راضية (وطب نفساً)، لأن الاعتراض المستمر يورث الهم والغم ولا يغير من الواقع شيئاً. ثم ينتقل الإمام إلى النهي الصارم عن 'الجزع' (ولا تجزع لحادثة الليالي). الجزع هو الانهيار النفسي المتمثل في الهلع والخوف المفرط وعدم تحمل الصدمات. الحياة مليئة بالحوادث والمصائب التي ترمز لها 'الليالي' بظلمتها وقسوتها. ولكن، لكي يتغلب الإنسان على هذا الخوف، يذكره الشافعي بحقيقة كونية كبرى: 'فما لحوادث الدنيا بقاء'. هذه الكلمات تمثل بلسماً لكل مجروح، فمهما طالت المصيبة، ومهما اشتد الكرب، فإنه حتماً سيزول. الدنيا دار فناء، ومصائبها تفنى معها. هذه النظرة الفلسفية العميقة تمنح الإنسان طاقة جبارة للتحمل وتجاوز الصعاب."
    },
    {
      id: 2,
      lineIndices: [5, 6, 7, 8],
      mlMeaning: "പ്രതിസന്ധികളിൽ ഉറച്ചുനിൽക്കുന്ന ധീരനാവുക, ഒപ്പം വിട്ടുവീഴ്ചയും വിശ്വസ്തതയും നിന്റെ സ്വഭാവമാക്കുക. ജനങ്ങൾക്കിടയിൽ നിനക്ക് ധാരാളം ന്യൂനതകൾ ഉണ്ടെങ്കിലും അതിനൊരു മറ ഉണ്ടായിരിക്കുന്നത് നിന്നെ സന്തോഷിപ്പിക്കുന്നുവെങ്കിൽ... ഒരു മനുഷ്യൻ എന്ന നിലയിൽ നാം എല്ലാവരും ന്യൂനതകൾ ഉള്ളവരാണ്. എന്നാൽ ആ ന്യൂനതകൾ മറ്റുള്ളവർ അറിയുന്നത് നാം ഇഷ്ടപ്പെടുന്നില്ല. ഈ ഒരു സാഹചര്യത്തിൽ നാം എങ്ങനെ പെരുമാറണം എന്നാണ് ഇവിടെ പറയുന്നത്. കാഠിന്യമുള്ള സാഹചര്യങ്ങളിലും വിട്ടുവീഴ്ചാമനോഭാവവും വിശ്വസ്തതയുമായിരിക്കണം നിന്റെ സ്വഭാവം. ഇത് നിന്റെ സകല ന്യൂനതകൾക്കും ഒരു മറയായി മാറും.",
      enMeaning: "Be a person of steadfast courage against terrors, while making magnanimity and loyalty your true character. And if your flaws become many among people, and you wish for a cover to conceal them... As humans, we all possess flaws and shortcomings. However, we naturally despise it when others discover them. Here, the Imam explains how we should conduct ourselves in such scenarios. Even in the most severe circumstances, your character must be defined by forgiveness, magnanimity, and loyalty. This will transform into an impenetrable cover for all your flaws.",
      arSharah: "يوجه الإمام الشافعي خطابه نحو بناء الشخصية الإنسانية المتكاملة القادرة على الصمود في وجه العواصف. 'وكن رجلاً على الأهوال جلداً'.. الجلد هو قوة الاحتمال، والصلابة في مواجهة المخاوف والصعاب (الأهوال). يريد منك أن تكون كالجبل الأشم لا تحركه الرياح العاتية. ولكن هذه الصلابة قد تتحول إلى قسوة وجفاء إذا لم تُزين بالأخلاق الرفيعة، ولذلك أردف قائلاً: 'وشيمتك السماحة والوفاء'. يجب أن يكون طبعك السائد وعلامتك الفارقة هي 'السماحة' (اللين والتسامح والكرم) و'الوفاء' (حفظ العهود وصدق الوعود). ثم يعرج الإمام على الطبيعة البشرية بصدق مذهل، فيقول: 'وإن كثرت عيوبك في البرايا'. كل إنسان مليء بالعيوب والنقائص، والفطرة السليمة تجعل الإنسان يخجل من انكشاف عيوبه ويسره 'أن يكون لها غطاء' يسترها عن عيون الناس (وسرك أن يكون لها غطاء). هذا التمهيد النفسي العبقري يجعلك في قمة الشوق لمعرفة ما هو هذا 'الغطاء' السحري الذي سيحجب عيوبك عن أعين المجتمع، وهو ما سيكشفه في الأبيات التالية."
    },
    {
      id: 3,
      lineIndices: [9, 10, 11, 12],
      mlMeaning: "...എങ്കിൽ ഔദാര്യം കൊണ്ട് നീ അത് മറയ്ക്കുക; സകല ന്യൂനതകളെയും ഔദാര്യം മായ്ച്ചുകളയും. അതുപോലെ, ശത്രുക്കളുടെ മുന്നിൽ നിന്റെ ബലഹീനത ഒരിക്കലും വെളിപ്പെടുത്തരുത്, കാരണം അവരുടെ പരിഹാസം കടുത്ത പരീക്ഷണമാണ്. നീ ഔദാര്യവാനാകുകയാണെങ്കിൽ ജനങ്ങൾ നിന്റെ ന്യൂനതകളെക്കാൾ നിന്റെ നന്മകൾക്കായിരിക്കും പ്രാധാന്യം നൽകുക. സകല ന്യൂനതകളെയും മായ്ച്ചുകളയാൻ കഴിവുള്ള അതിവിശിഷ്ടമായ ഒരു ഗുണമാണ് ഔദാര്യം. ശത്രുക്കളുടെ മുന്നിൽ ഒരു കാരണവശാലും നീ നിന്റെ നിസ്സഹായത പ്രകടിപ്പിക്കരുത്. ശത്രുക്കളുടെ പരിഹാസം ഏത് വലിയ ദുരന്തത്തെക്കാളും വേദനിപ്പിക്കുന്നതാണ്.",
      enMeaning: "...then cloak yourself in generosity, for it conceals every flaw as the wise have said. Furthermore, never show an ounce of weakness to your enemies, as their malicious gloating is an unbearable affliction. If you become magnanimous, people will prioritize your goodness over your flaws. Generosity is an exquisitely noble trait capable of erasing all shortcomings. Under no circumstances should you ever display your helplessness before your enemies. The derisive mockery of enemies is infinitely more painful than the grandest tragedy.",
      arSharah: "يقدم الإمام الشافعي هنا العلاج الناجع والوصفة السحرية لمشكلة العيوب البشرية: 'تستر بالسخاء'. السخاء ليس مجرد إنفاق المال، بل هو كرم النفس، وسعة الصدر، وحسن الخلق، والتجاوز عن زلات الآخرين. فالمجتمع مجبول على محبة الكريم والتغاضي عن أخطائه. 'فكل عيب يغطيه كما قيل السخاء'.. إن كرمك ومروءتك سيجعلان الناس يغضون الطرف عن نواقصك ويركزون على إحسانك. هذه الحكمة الاجتماعية أثبتت فعاليتها عبر العصور. ثم ينتقل الشافعي بحزم للحديث عن 'عزة النفس'، محذراً تحذيراً شديداً ومطلقاً (استخدام 'قط') من إظهار أي شكل من أشكال الضعف أو الانكسار أمام الأعداء (ولا تر للأعادي قط ذلاً). لماذا؟ لأن 'شماتة الأعدا بلاء'. الشماتة هي فرح العدو وحبوره بمصيبتك، وهي تقع في النفس موقعاً أشد إيلاماً وتدميراً من المصيبة نفسها. رؤية الابتسامة الشامتة على وجه الخصم تمزق نياط القلب. لذا، يطالبك الشاعر بأن تتجمل بالصبر وتتصنع القوة مهما كنت تتألم من الداخل، حتى لا تمنح أعداءك لذة الانتصار برؤية انكسارك."
    },
    {
      id: 4,
      lineIndices: [13, 14, 15, 16],
      mlMeaning: "പിശുക്കനിൽ നിന്ന് ഒരിക്കലും നന്മ പ്രതീക്ഷിക്കരുത്, ദാഹിക്കുന്നവന് തീയിൽ നിന്ന് വെള്ളം കിട്ടാത്തത് പോലെയാണത്. നിന്റെ ഉപജീവനം സാവകാശം കാണിക്കുന്നതുകൊണ്ട് കുറയുകയോ അമിതമായി കഷ്ടപ്പെടുന്നതുകൊണ്ട് വർദ്ധിക്കുകയോ ഇല്ല. ഒട്ടും നന്മയില്ലാത്ത ഒരു പിശുക്കനിൽ നിന്ന് നീ ഒരിക്കലും വിട്ടുവീഴ്ചയോ ഔദാര്യമോ പ്രതീക്ഷിക്കരുത്. അങ്ങനെയുള്ളവനിൽ നിന്ന് സഹായം പ്രതീക്ഷിക്കുന്നത് ദാഹിക്കുന്നവൻ തീയിൽ നിന്ന് വെള്ളം ചോദിക്കുന്നതിന് തുല്യമാണ്. സാവകാശം കാണിക്കുന്നതുകൊണ്ട് നിനക്ക് നിശ്ചയിക്കപ്പെട്ട ഉപജീവനം ഒരിക്കലും കുറഞ്ഞുപോകില്ല. അതുപോലെ തന്നെ, അമിതമായ ആയാസവും കഷ്ടപ്പാടും ഒരിക്കലും നിന്റെ ഉപജീവനത്തിൽ യാതൊരു വർദ്ധനവും വരുത്തുകയുമില്ല.",
      enMeaning: "Do not expect generosity from a miser; it is like a thirsty man seeking water in a fire. Your destined provision will not decrease through patience, nor will it miraculously increase through exhausting toil. Never hope for forgiveness or magnanimity from a deeply miserly person wholly devoid of goodness. Expecting help from such a person is exactly equivalent to a thirsty person asking a blazing fire for water. Taking your time with deliberation will never diminish the sustenance preordained for you. Likewise, excessive exertion and immense hardship will never bring about any increase in your wealth or provision.",
      arSharah: "في هذا المقطع، يوجه الشافعي نصيحة قوية تحفظ كرامة الإنسان وتصون ماء وجهه: 'ولا ترج السماحة من بخيل'. البخيل هنا لا يقتصر على بخيل المال، بل يشمل بخيل المشاعر واللئيم الذي لا يعرف المروءة. طلب العون من هؤلاء هو إهانة للنفس وإذلال لها دون طائل. ولترسيخ هذه الفكرة، يضرب مثلاً بلاغياً رائعاً: 'فما في النار للظمآن ماء'. فكما يستحيل أن يجد العطشان الذي يكاد يهلك من الظمأ قطرة ماء ترويه داخل كتلة من النار المشتعلة، فإنه يستحيل أن تجد خيراً أو كرماً عند اللئيم. ثم يعالج الشافعي قضية 'الرزق' التي تشغل بال الكثيرين وتسبب لهم القلق والتوتر الدائم. يقرر قاعدتين ذهبيتين: 'ورزقك ليس ينقصه التأني'، أي أن هدوءك وأخذك بالأسباب بسكينة وحكمة لن ينقص من رزقك المكتوب لك شيئاً. 'وليس يزيد في الرزق العناء'، أي أن لهاثك المحموم، وتعبك المفرط، وركضك الهستيري خلف الدنيا لن يضيف درهماً واحداً إلى ما قدره الله لك. هذه الرؤية تدعو إلى التوكل الصادق، والعمل باعتدال، والتحرر من عبودية المادة."
    },
    {
      id: 5,
      lineIndices: [17, 18, 19, 20],
      mlMeaning: "സന്തോഷവും ദുഃഖവും ദാരിദ്ര്യവും സമ്പന്നതയും ഇവിടെ ശാശ്വതമല്ല. സംതൃപ്തമായ ഒരു ഹൃദയമാണ് നിനക്കുള്ളതെങ്കിൽ, നീയും ഈ ലോകത്തിന്റെ രാജാവും പൂർണ്ണമായും തുല്യരാണ്. ഈ ലോകത്ത് ദുഃഖം ശാശ്വതമല്ല, സന്തോഷവും ശാശ്വതമല്ല. അതുപോലെ, നിങ്ങൾ അനുഭവിക്കുന്ന കഷ്ടപ്പാടുകളും ദാരിദ്ര്യവും നിത്യമായിരിക്കില്ല, നിങ്ങൾ അനുഭവിക്കുന്ന സുഖസൗകര്യങ്ങളും നിലനിൽക്കുന്നതല്ല. ലഭിച്ചതിൽ സംതൃപ്തി കണ്ടെത്തുന്ന ഹൃദയം നിനക്കുണ്ടെങ്കിൽ ഈ ലോകം മുഴുവൻ സ്വന്തമാക്കിയ രാജാവും നീയും തമ്മിൽ ഒരു വ്യത്യാസവുമില്ല.",
      enMeaning: "No joy or sorrow is eternal, nor is any state of misery or prosperity permanent. If you possess a contented heart, then you and the master of this world are absolutely equal. In this world, sorrow is not eternal, and joy is not eternal either. Similarly, the hardships and poverty you experience will not last forever, nor are the comforts and luxuries you enjoy permanent. If you have a heart that finds absolute contentment in what it has received, then there is not a single difference between you and the king who has conquered the entire world.",
      arSharah: "يصل الإمام الشافعي في هذا المقطع إلى قمة الحكمة والفلسفة الحياتية العميقة. يقرر حقيقة كونية لا جدال فيها: قانون 'التغير المستمر'. 'ولا حزن يدوم ولا سرور.. ولا بؤس عليك ولا رخاء'. لا توجد حالة إنسانية ثابتة في هذه الدنيا. فالحزن سينقشع، والسرور سيزول، والفقر والشدة (البؤس) سيرفعان، والغنى والدعة (الرخاء) سيتغيران. هذا الإدراك العميق لطبيعة الحياة يمنح الإنسان توازناً نفسياً مذهلاً؛ فلا يطير فرحاً عند النعمة حتى ينسى المنعم، ولا ينهار جزعاً عند المصيبة وكأنها نهاية العالم. ثم يتوج الشافعي هذه الحكمة بالوصول إلى سر السعادة الحقيقية والغنى المطلق: 'إذا ما كنت ذا قلب قنوع.. فأنت ومالك الدنيا سواء'. القناعة هي الغنى الحقيقي. الشخص الذي يمتلك قلباً راضياً بما قسمه الله له، لا يشعر بنقص ولا يلهث وراء المزيد بجشع. هذا الإنسان القنوع يتساوى في ميزان السعادة والراحة النفسية مع 'مالك الدنيا' بأسرها، لأن الغاية من جمع الدنيا هي تحصيل الراحة، والقنوع قد حصل على هذه الراحة بأقصر الطرق وأطهرها."
    },
    {
      id: 6,
      lineIndices: [21, 22, 23, 24],
      mlMeaning: "മരണം ആരുടെയെങ്കിലും മുറ്റത്ത് വന്നിറങ്ങിയാൽ, അവനെ രക്ഷിക്കാൻ ഭൂമിക്കോ ആകാശത്തിനോ കഴിയില്ല. അല്ലാഹുവിന്റെ ഭൂമി വിശാലമാണ്, എന്നാൽ വിധി വന്നെത്തുമ്പോൾ ബഹിരാകാശം പോലും ഇടുങ്ങിയതായി മാറും. മരണം വന്നെത്തിയാൽ ആർക്കും അതിൽ നിന്ന് രക്ഷപ്പെടാൻ കഴിയില്ല. എത്ര വലിയ കാവൽക്കാരുണ്ടെങ്കിലും മരണത്തെ തടയാൻ ആർക്കും കഴിയില്ല. ഭൂമി എത്ര വിശാലമാണെങ്കിലും വിധി വന്നെത്തുമ്പോൾ അത് ഇടുങ്ങിയതായി മാറും. അതായത് വിധിയിൽ നിന്ന് ഒളിച്ചോടാൻ ആർക്കും കഴിയില്ല.",
      enMeaning: "When death descends upon a person's courtyard, neither earth nor sky can protect him. Allah's earth is vast, yet when the divine decree arrives, even the vastness of space becomes narrow. Once death arrives, no one can ever escape it. No matter how formidable your guards or fortresses are, no one can stop death. No matter how infinitely vast the earth is, when destiny strikes, it instantly becomes devastatingly narrow. This means that absolutely no one can run or hide from the final decree.",
      arSharah: "في هذا المقطع التراجيدي والمهيب، يذكر الإمام الشافعي بـ 'الحقيقة المطلقة' التي يغفل عنها الكثيرون: حتمية الموت وقهر القدر. 'ومن نزلت بساحته المنايا.. فلا أرض تقيه ولا سماء'. إذا حان الأجل، ونزل طائر الموت (المنايا) في فناء دار الإنسان (ساحته)، فلا يوجد ملاذ يفر إليه، ولا حصن يحميه. تسقط كل أسباب الحماية الأرضية من مال وسلطان وحراس، وتغلق أبواب السماء فلا يرد القدر. الموت قوة قاهرة لا تقف أمامها أي قوة بشرية. ثم يصور الشافعي حالة الاختناق والعجز التام أمام القدر: 'وأرض الله واسعة ولكن.. إذا نزل القضا ضاق الفضاء'. الكون بأسره، رغم اتساعه الهائل ورحابته، يضيق على الإنسان وتنسد في وجهه كل الدروب والمنافذ إذا نفذ فيه قضاء الله وقدره. هذا التصوير البليغ لضيق الفضاء يشعر المتلقي بمدى ضعف الإنسان وهوانه أمام إرادة الخالق، مما يدفعه إلى التواضع والتخلي عن الغرور والتكبر، واللجوء الدائم إلى الله."
    },
    {
      id: 7,
      lineIndices: [25, 26],
      mlMeaning: "അതിനാൽ എപ്പോഴും ചതിക്കുന്ന കാലത്തെ അതിന്റെ പാട്ടിന് വിടുക; മരണം വന്നെത്തുമ്പോൾ ഒരു മരുന്നും അതിനെ തടയാൻ ഫലം ചെയ്യില്ല. കാലം എപ്പോഴും മാറിമറിയുന്നതാണ്. ഇന്നത്തെ അവസ്ഥയായിരിക്കില്ല നാളത്തേത്. അതുകൊണ്ട് തന്നെ കാലത്തിന്റെ മാറ്റങ്ങളിൽ വിശ്വസിക്കരുത്. മരണം വന്നെത്തിയാൽ പിന്നെ ഒരു മരുന്നിനും നമ്മെ രക്ഷിക്കാൻ കഴിയില്ല. അതുകൊണ്ട് തന്നെ മരണത്തിന് മുൻപ് പരലോകത്തിന് വേണ്ടി സൽകർമ്മങ്ങൾ ചെയ്യുക.",
      enMeaning: "Therefore, leave the days that constantly betray; when death finally comes, no medicine whatsoever will avail against it. Time is constantly in flux and highly deceptive. Today's condition will not be tomorrow's. Therefore, never put your absolute trust in the changing nature of time. Once death arrives, no medicine or advanced science can possibly save us. Therefore, diligently perform profoundly righteous deeds for the Hereafter before death arrives.",
      arSharah: "يختتم الإمام الشافعي قصيدته الرائعة بالعودة إلى فكرتها الأولى المركزية، ولكن مع تكثيف درامي أعمق. 'دع الأيام تغدر كل حين'. يكرر الأمر بترك الأيام وتجنب الركون إليها، لأن من طبيعتها 'الغدر'. الدنيا خداعة، تعطي لتأخذ، وترفع لتخفض، وتبتسم لتكشر عن أنيابها. الركون إلى الدنيا والاطمئنان إليها هو قمة الوهم والجهل. وفي الشطر الأخير 'فما يغني عن الموت الدواء'، يضرب الشافعي الضربة القاضية لكل أوهام الخلود البشري. مهما تقدم الطب، ومهما تعددت الأدوية والأسباب، فإنها تقف جميعاً عاجزة مشلولة أمام سكرات الموت. الموت هو النهاية الحتمية التي لا مفر منها. هذه الخاتمة القوية ليست دعوة لليأس والإحباط، بل هي دعوة لإيقاظ الغافلين، وتصحيح البوصلة نحو الاستعداد للآخرة، والعمل الصالح، وعدم الاغترار بمتاع الدنيا الزائل. إنها رسالة لترتيب الأولويات وإعطاء كل شيء حجمه الحقيقي."
    }
  ]`;

content = content.replace(/  quatrains: \[\s*\{[\s\S]*\}\s*\]/g, massiveQuatrains);

fs.writeFileSync('src/data/shafiee-da-al-ayyam/poemData.ts', content);
console.log('Successfully injected massive ultra mega detailed quatrains for Shafiee poem!');
